### ISSUE TITLE
AUR Chrome not found on Manjaro Linux

### ISSUE THREAD

**Issue by waynebloss** [dart-lang/browser_launcher#16]
Manjaro (and I'm assuming Arch Linux) gets the one and only `google-chrome` package installed at `/usr/bin/google-chrome-stable` so `browser_launcher` fails to launch it there.

Linking `/usr/bin/google-chrome` to the startup executable fixed the problem.

Not sure if you care enough to change anything, but you can read about my journey to this issue while using VS Code with Dart-Code at Dart-Code/Dart-Code#1830. Here's the error that I got:

```
Failed to launch browser: ProcessException: No such file or directory
  Command: google-chrome http://127.0.0.1:9100/?hide=debugger&ide=VSCode&theme=dark&uri=http%3A%2F%2F127.0.0.1%3A38507%2F16GEBer2mu0%3D%2F
#0      Chrome._startProcess (package:browser_launcher/src/chrome.dart:130:12)
<asynchronous suspension>
#1      Chrome.start (package:browser_launcher/src/chrome.dart:122:18)
#2      registerLaunchDevToolsService.<anonymous closure> (package:devtools_server/src/server.dart:425:24)
```

**Comment by strimmlarn** [comment]
Had same problem. 

below code inside a folder linked to PATH solved it for me: 
`ln -s /usr/bin/chromium ./google-chrome`
